[pytest]
markers =
    api: Chay cac test case ve API
    ui: Chay cac test case ve UI (Playwright)
    backend: Chay cac test case ve Backend
    component: Chay cac test case component
    blackbox: Chay cac test case blackbox
    unit: Chay cac test case unit