name: SDET Backend Automation CI

# Kích hoạt pipeline mỗi khi có code push lên nhánh main hoặc tạo Pull Request
on:
  push:
    branches: [ "main", "master", "cicd-allure" ]
  pull_request:
    branches: [ "main", "master"]

jobs:
  run-tests:
    runs-on: ubuntu-latest # Sử dụng máy chủ Ubuntu do GitHub cấp miễn phí

    permissions:
      contents: write 
      pages: write
      id-token: write

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11']

    steps:
    # Clone code từ repo của bạn xuống máy chủ GitHub
    - name: 📥 Checkout code
      uses: actions/checkout@v4

    # Caching
    - name: 🐍 Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with: 
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    # STATIC CODE ANALYSIS: Chặn mã rác trước khi chạy Test
    - name: 🧹 Linter & Code Quality (Ruff)
      run: |
        python -m pip install ruff
        ruff check .

    # Bật các hệ thống vệ tinh (DB & Kafka) bằng file Docker Compose bạn đã viết
    - name: 🐳 Spin up Infrastructure (PostgreSQL & Kafka)
      run: |
        docker compose up -d --wait
        echo "--- DB is healthy, waiting for init_schema.sql to finish... ---"
        sleep 5
        echo "--- DANH SÁCH CONTAINER ĐANG CHẠY ---"
        docker ps -a 
        echo "--- LOG CỦA POSTGRESQL ---"
        docker logs qa-postgres-db

    # Cài đặt các thư viện (pytest, confluent-kafka, v.v.)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Cache Playwright browers
      uses: actions/cache@v4
      id: playwright-cache
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-playwright-

    - name: Install Playwright browsers
      if: | 
        !steps.playwright-cache.outputs.cache-hit
      run: |
        python -m playwright install --with-deps

    # Chạy Test và sinh dữ liệu Allure Report
    - name: Run Pytest
      run: |
        pytest tests/ --alluredir=allure-results
      env:
        # Bạn có thể ghi đè biến môi trường ở đây nếu cần thiết
        KAFKA_BROKER: localhost:9092
        DB_HOST: localhost
        DB_USER: app
        DB_PASSWORD: app
        DB_NAME: app

    # Thu thập kết quả Test (Kể cả khi Test Fail vẫn phải chạy bước này)
    - name: Upload Allure Results
      uses: actions/upload-artifact@v4
      if: always() 
      with:
        name: allure-results
        path: allure-results
        retention-days: 7

    # 1. Biến cục data JSON/XML thành trang HTML giao diện đẹp (giữ lại cả lịch sử trend)
    - name: 📊 Generate Allure Report
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: allure-results
        allure_history: allure-history
        keep_reports: 20 # Lưu lại biểu đồ trend của 20 lần chạy gần nhất

    # 2. Bê nguyên thư mục HTML đó ném lên GitHub Pages (Nhánh gh-pages)
    - name: 🚀 Deploy Allure Report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history